name: Daily Sports Schedules and Standings

on:
  schedule:
  # This is in UTC - https://crontab.guru
  - cron: "0 12 * * *" 
  # Allow for manual triggering
  workflow_dispatch:

env:
  MAIL_USER_EMAIL: ${{ secrets.MAIL_USER_EMAIL }}
  MAIL_USER_PASSWORD: ${{ secrets.MAIL_USER_PASSWORD }}
  MAIL_FROM: ${{ secrets.MAIL_FROM }}
  MAIL_TO: ${{ secrets.MAIL_TO }}

jobs:
  report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: node src/main.js
